import { createClient } from "npm:@supabase/supabase-js@2.57.2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

const NOTION_API = "https://api.notion.com/v1";
const NOTION_VERSION = "2022-06-28";

function chunkText(text: string, size = 1900): string[] {
  const out: string[] = [];
  for (let i = 0; i < text.length; i += size) out.push(text.slice(i, i + size));
  return out.length ? out : [""];
}

function paragraphBlock(text: string) {
  return {
    object: "block",
    type: "paragraph",
    paragraph: {
      rich_text: chunkText(text).map((t) => ({ type: "text", text: { content: t } })),
    },
  };
}

function headingBlock(text: string, level: 1 | 2 = 2) {
  const type = `heading_${level}`;
  return {
    object: "block",
    type,
    [type]: {
      rich_text: [{ type: "text", text: { content: text } }],
    },
  };
}

function codeBlock(text: string) {
  return {
    object: "block",
    type: "code",
    code: {
      language: "markdown",
      rich_text: chunkText(text).map((t) => ({ type: "text", text: { content: t } })),
    },
  };
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const NOTION_API_KEY = Deno.env.get("NOTION_API_KEY");
    if (!NOTION_API_KEY) {
      return new Response(
        JSON.stringify({
          error: "NOTION_API_KEY not configured. Add a Notion integration token to enable export.",
          code: "missing_token",
        }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const authHeader = req.headers.get("Authorization");
    if (!authHeader) throw new Error("Missing Authorization header");
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
      { global: { headers: { Authorization: authHeader } } }
    );
    const { data: userData, error: userError } = await supabase.auth.getUser(
      authHeader.replace("Bearer ", "")
    );
    if (userError || !userData.user) throw new Error("Not authenticated");

    const body = await req.json().catch(() => ({}));
    const { action, projectId, parentPageId, query } = body as {
      action?: "search" | "create";
      projectId?: string;
      parentPageId?: string;
      query?: string;
    };

    const notionFetch = (path: string, init: RequestInit) =>
      fetch(`${NOTION_API}${path}`, {
        ...init,
        headers: {
          Authorization: `Bearer ${NOTION_API_KEY}`,
          "Notion-Version": NOTION_VERSION,
          "Content-Type": "application/json",
          ...(init.headers || {}),
        },
      });

    // ── Search: list pages the integration has access to ──
    if (action === "search") {
      const res = await notionFetch("/search", {
        method: "POST",
        body: JSON.stringify({
          query: query || "",
          filter: { value: "page", property: "object" },
          page_size: 25,
        }),
      });
      const data = await res.json();
      if (!res.ok) {
        return new Response(JSON.stringify({ error: data?.message || "Notion search failed" }), {
          status: res.status,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      const pages = (data.results ?? []).map((p: any) => {
        const titleProp = p.properties && Object.values(p.properties).find((pr: any) => pr.type === "title") as any;
        const title = titleProp?.title?.[0]?.plain_text
          || p.properties?.title?.title?.[0]?.plain_text
          || "Untitled";
        return { id: p.id, title };
      });
      return new Response(JSON.stringify({ pages }), {
        status: 200,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // ── Create: push spec as a child page ──
    if (action === "create") {
      if (!projectId || !parentPageId) {
        return new Response(JSON.stringify({ error: "projectId and parentPageId required" }), {
          status: 400,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      const { data: project, error: projErr } = await supabase
        .from("projects")
        .select("title, brief, spec, confidence, approved")
        .eq("id", projectId)
        .single();
      if (projErr || !project) throw new Error("Project not found");
      if (!project.approved) throw new Error("Project must be approved before exporting");

      const children = [
        paragraphBlock(`Confidence: ${project.confidence ?? 0}% · Generated by SpecMirror`),
        headingBlock("Brief", 2),
        paragraphBlock(project.brief || "(empty)"),
        headingBlock("Specification", 2),
        codeBlock(project.spec || "(empty)"),
      ];

      const res = await notionFetch("/pages", {
        method: "POST",
        body: JSON.stringify({
          parent: { type: "page_id", page_id: parentPageId },
          properties: {
            title: { title: [{ type: "text", text: { content: project.title } }] },
          },
          children,
        }),
      });
      const data = await res.json();
      if (!res.ok) {
        return new Response(JSON.stringify({ error: data?.message || "Notion page create failed" }), {
          status: res.status,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      return new Response(JSON.stringify({ success: true, url: data.url, pageId: data.id }), {
        status: 200,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    return new Response(JSON.stringify({ error: "Unknown action" }), {
      status: 400,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Unknown error";
    return new Response(JSON.stringify({ error: msg }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});